name: Deploy Acess Drivers

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: . # Publica a pasta onde está o seu index.html
          branch: gh-pages # Cria uma branch só para o site online
